language: python
python:
  - 2.7
  - 3.5
branches:
  only:
    - master
notifications:
  email: false

# Setup anaconda
before_install:
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - bash continuous-integration/travis/install.sh

# Run test
script:
  - "coverage run --source=praatinterface setup.py test"

# Calculate coverage
after_success:
  - coveralls

cache:
  directories:
    - $HOME/downloads
    - $HOME/miniconda
  apt: true
