language: python
python:
  - 3.5
  - 3.6
branches:
  only:
    - master
notifications:
  email: false

sudo: false

# Install packages
before_install:
  - bash continuous-integration/travis/install.sh

install:
  - export PATH="$HOME/miniconda/miniconda/bin:$PATH"
  - source activate "test-environment$TRAVIS_PYTHON_VERSION"
  - which python
  - conda list

# Run test
script:
  - "coverage run --source=pyraat setup.py test"

# Calculate coverage
after_success:
  - coveralls

cache:
  directories:
    - $HOME/downloads
    - $HOME/tools
    - $HOME/miniconda
