language: python
python:
  - 2.7
  - 3.5
branches:
  only:
    - master
notifications:
  email: false

sudo: false

# Install packages
install:
  - bash continuous-integration/travis/install.sh

# Run test
script:
  - "coverage run --source=praatinterface setup.py test"

# Calculate coverage
after_success:
  - coveralls

cache:
  directories:
    - $HOME/downloads
    - $HOME/tools
    - $HOME/miniconda
